In [13]:
import numpy as np

In [14]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [15]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [18]:
type(arr1)

numpy.ndarray

nd = n-Dimensional

In [21]:
arr2 = np.arange(10, 20, 1) # (start, stop (non-inclusive), step-size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
list1

[10, 20, 30]

In [23]:
list2 = [40, 50, 60]

In [24]:
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [25]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [26]:
arr3.shape

(2, 3)

In [28]:
arr3dim = np.array(
    [
        [
            [1, 2, 3], [3, 4, 5]
        ],
        [
            [5, 6, 7], [7, 8, 9]
        ]
    ]
)
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [29]:
arr3dim.shape

(2, 2, 3)

# Matrix Operations

In [30]:
list1

[10, 20, 30]

In [31]:
list1 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [32]:
arr1

array([10, 20, 30])

In [34]:
arr1 * 3

array([30, 60, 90])

In [35]:
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [36]:
arr1

array([10, 20, 30])

In [39]:
arr11 = np.array(list2)

In [40]:
arr11

array([40, 50, 60])

In [41]:
arr1.shape == arr11.shape

True

In [42]:
arr1 * arr11

array([ 400, 1000, 1800])

In [43]:
arr1.shape, arr2.shape

((3,), (10,))

In [44]:
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,) (10,) 

In [45]:
arr1

array([10, 20, 30])

In [46]:
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [47]:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

# Lab
Create ndarrays of the following sizes:
1. One dimensional array with 12 elements (12,)
2. Two dimensionl array of size (3, 4)
3. Three dimensional array of size (2, 5, 4)


In [49]:
q1l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
q1l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [51]:
q1a = np.array(q1l)
q1a, q1a.shape

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), (12,))

In [62]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = [7, 8, 9, 10]
a = [x, y, z]
a

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]]

In [63]:
q2a = np.array(a)
q2a, q2a.shape

(array([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]]),
 (3, 4))

In [65]:
a3 = np.array(
    [
        [[1, 2, 3, 4], [3, 4, 5, 6], [5, 6 , 7, 8], [5, 6, 7, 8], [4, 5, 2, 1]],
        [[1, 2, 4, 3], [3, 2, 4, 6], [5, 6 , 9, 8], [5, 1, 7, 8], [4, 5, 10, 1]]
    ]
)
a3.shape

(2, 5, 4)

In [66]:
np.zeros(12,)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
np.zeros((2, 5, 4), dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [70]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [73]:
arr1

array([10, 20, 30])

In [74]:
arr1[1]

20

In [75]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [76]:
arr3[1][2]

60

In [77]:
arr3[0]

array([10, 20, 30])

In [78]:
arr3[:,1]

array([20, 50])

In [79]:
arr3dim[1]

array([[5, 6, 7],
       [7, 8, 9]])

In [80]:
arr3dim[1,1,0]

7

In [82]:
arr3dim[:,:,1]

array([[2, 4],
       [6, 8]])

In [84]:
arr3dim.sum()

60

In [85]:
arr3dim.mean()

5.0

In [86]:
arr3dim.std()

2.3804761428476167

In [88]:
arr3dim.mean(0)

array([[3., 4., 5.],
       [5., 6., 7.]])

In [89]:
arr3dim.mean(1)

array([[2., 3., 4.],
       [6., 7., 8.]])

In [90]:
arr3dim.mean(2)

array([[2., 4.],
       [6., 8.]])

In [92]:
arr3dim.var()

5.666666666666667

In [94]:
arr3dim.min()

1

In [95]:
arr3dim.max()

9

In [96]:
for dim in arr3:
    print(dim)

[10 20 30]
[40 50 60]


In [99]:
for dim in arr3:
    for x in dim:
        print(x)

10
20
30
40
50
60


In [100]:
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


In [101]:
np.save("new_array", arr3)

In [103]:
np.load("new_array.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [104]:
np.savetxt("new_array.txt", arr3, delimiter='\t')

In [105]:
np.loadtxt("new_array.txt", delimiter='\t')

array([[10., 20., 30.],
       [40., 50., 60.]])